import os

# Database Configuration
DATABASE_URL = os.getenv("DATABASE_URL")

# Azure OpenAI Configuration
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2025-01-01-preview")

# Azure OpenAI Embedding Configuration
AZURE_OPENAI_EMBEDDING_ENDPOINT = os.getenv("AZURE_OPENAI_EMBEDDING_ENDPOINT")
AZURE_OPENAI_EMBEDDING_API_KEY = os.getenv("AZURE_OPENAI_EMBEDDING_API_KEY")
AZURE_OPENAI_EMBEDDING_API_VERSION = os.getenv("AZURE_OPENAI_EMBEDDING_API_VERSION", "2023-05-15")

# File Upload Configuration
UPLOAD_DIR = os.getenv("UPLOAD_DIR", "/tmp/uploads")

# LLM Token Limits
LLM_MAX_INPUT_TOKENS = 10000
LLM_MAX_OUTPUT_TOKENS = 16000

# Azure OpenAI Whisper Configuration
AZURE_WHISPER_ENDPOINT = os.getenv("AZURE_WHISPER_ENDPOINT")
AZURE_WHISPER_API_KEY = os.getenv("AZURE_WHISPER_API_KEY")
AZURE_WHISPER_DEPLOYMENT_NAME = os.getenv("AZURE_WHISPER_DEPLOYMENT_NAME", "whisper")
AZURE_WHISPER_API_VERSION = os.getenv("AZURE_WHISPER_API_VERSION", "2024-06-01")

# Azure Blob Storage Configuration
AZURE_STORAGE_ACCOUNT_NAME = os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
AZURE_STORAGE_ACCOUNT_KEY = os.getenv("AZURE_STORAGE_ACCOUNT_KEY")
AZURE_STORAGE_CONTAINER_NAME = os.getenv("AZURE_STORAGE_CONTAINER_NAME")
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

# Webhook Configuration
FASTAPI_WEBHOOK_URL = os.getenv("FASTAPI_WEBHOOK_URL")
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")

# Queue Configuration
DOCUMENT_PROCESSING_QUEUE = os.getenv("DOCUMENT_PROCESSING_QUEUE", "document-processing")
QUICKBOOK_PROCESSING_QUEUE = os.getenv("QUICKBOOK_PROCESSING_QUEUE", "quickbook-processing")
CARBONVOICE_PROCESSING_QUEUE = os.getenv("CARBONVOICE_PROCESSING_QUEUE", "carbonvoice-processing")

# QuickBooks Webhook Configuration
QUICKBOOK_WEBHOOK_URL = os.getenv("QUICKBOOK_WEBHOOK_URL")

# Carbon Voice Webhook Configuration
CARBONVOICE_WEBHOOK_URL = os.getenv("CARBONVOICE_WEBHOOK_URL")
