/**
 * Acronyms Library
 *
 * Business and financial acronym definitions used throughout the application.
 * Used by AcronymTooltip component to provide contextual definitions.
 */

export interface AcronymDefinition {
  /** The acronym (e.g., "ARR") */
  acronym: string;
  /** Full expansion (e.g., "Annual Recurring Revenue") */
  fullName: string;
  /** Brief description/definition */
  description: string;
  /** Category for grouping */
  category: 'financial' | 'customer' | 'sales' | 'product' | 'operations' | 'general';
}

/**
 * Complete list of business acronyms with definitions
 */
export const ACRONYMS: Record<string, AcronymDefinition> = {
  // Financial Metrics
  ARR: {
    acronym: 'ARR',
    fullName: 'Annual Recurring Revenue',
    description: 'The value of recurring revenue normalized to a one-year period. Key SaaS metric for measuring predictable revenue.',
    category: 'financial',
  },
  MRR: {
    acronym: 'MRR',
    fullName: 'Monthly Recurring Revenue',
    description: 'The predictable revenue a company expects to receive every month from active subscriptions.',
    category: 'financial',
  },
  TCV: {
    acronym: 'TCV',
    fullName: 'Total Contract Value',
    description: 'The total value of a customer contract, including all recurring and one-time fees.',
    category: 'financial',
  },
  ACV: {
    acronym: 'ACV',
    fullName: 'Annual Contract Value',
    description: 'The average annual revenue per customer contract, excluding one-time fees.',
    category: 'financial',
  },
  EBITDA: {
    acronym: 'EBITDA',
    fullName: 'Earnings Before Interest, Taxes, Depreciation, and Amortization',
    description: 'A measure of operating performance that excludes non-operating expenses.',
    category: 'financial',
  },
  GM: {
    acronym: 'GM',
    fullName: 'Gross Margin',
    description: 'Revenue minus cost of goods sold, expressed as a percentage of revenue.',
    category: 'financial',
  },
  COGS: {
    acronym: 'COGS',
    fullName: 'Cost of Goods Sold',
    description: 'Direct costs attributable to producing goods or services sold.',
    category: 'financial',
  },
  DSO: {
    acronym: 'DSO',
    fullName: 'Days Sales Outstanding',
    description: 'Average number of days to collect payment after a sale. Lower is better.',
    category: 'financial',
  },
  FCF: {
    acronym: 'FCF',
    fullName: 'Free Cash Flow',
    description: 'Cash generated by operations minus capital expenditures.',
    category: 'financial',
  },

  // Customer Metrics
  NRR: {
    acronym: 'NRR',
    fullName: 'Net Revenue Retention',
    description: 'Percentage of recurring revenue retained from existing customers, including expansions and contractions. Above 100% indicates growth from existing customers.',
    category: 'customer',
  },
  GRR: {
    acronym: 'GRR',
    fullName: 'Gross Revenue Retention',
    description: 'Percentage of recurring revenue retained from existing customers, excluding expansions. Maximum is 100%.',
    category: 'customer',
  },
  NPS: {
    acronym: 'NPS',
    fullName: 'Net Promoter Score',
    description: 'Customer loyalty metric ranging from -100 to +100, based on likelihood to recommend.',
    category: 'customer',
  },
  CSAT: {
    acronym: 'CSAT',
    fullName: 'Customer Satisfaction Score',
    description: 'Measure of customer satisfaction with a product, service, or interaction.',
    category: 'customer',
  },
  LTV: {
    acronym: 'LTV',
    fullName: 'Lifetime Value',
    description: 'Total revenue expected from a customer over their entire relationship with the company.',
    category: 'customer',
  },
  CLV: {
    acronym: 'CLV',
    fullName: 'Customer Lifetime Value',
    description: 'Same as LTV - total predicted revenue from a customer relationship.',
    category: 'customer',
  },
  DAU: {
    acronym: 'DAU',
    fullName: 'Daily Active Users',
    description: 'Number of unique users who engage with a product in a single day.',
    category: 'customer',
  },
  MAU: {
    acronym: 'MAU',
    fullName: 'Monthly Active Users',
    description: 'Number of unique users who engage with a product within a month.',
    category: 'customer',
  },
  WAU: {
    acronym: 'WAU',
    fullName: 'Weekly Active Users',
    description: 'Number of unique users who engage with a product within a week.',
    category: 'customer',
  },

  // Sales Metrics
  CAC: {
    acronym: 'CAC',
    fullName: 'Customer Acquisition Cost',
    description: 'Total cost of acquiring a new customer, including marketing and sales expenses.',
    category: 'sales',
  },
  LTV_CAC: {
    acronym: 'LTV:CAC',
    fullName: 'LTV to CAC Ratio',
    description: 'Ratio of customer lifetime value to acquisition cost. 3:1 or higher is generally healthy.',
    category: 'sales',
  },
  CAC_PAYBACK: {
    acronym: 'CAC Payback',
    fullName: 'CAC Payback Period',
    description: 'Months required to recover customer acquisition cost from subscription revenue.',
    category: 'sales',
  },
  SQL: {
    acronym: 'SQL',
    fullName: 'Sales Qualified Lead',
    description: 'A lead that has been vetted by sales and meets criteria for direct sales engagement.',
    category: 'sales',
  },
  MQL: {
    acronym: 'MQL',
    fullName: 'Marketing Qualified Lead',
    description: 'A lead deemed more likely to become a customer based on marketing engagement.',
    category: 'sales',
  },
  SAL: {
    acronym: 'SAL',
    fullName: 'Sales Accepted Lead',
    description: 'A lead that sales has accepted and committed to follow up on.',
    category: 'sales',
  },
  AE: {
    acronym: 'AE',
    fullName: 'Account Executive',
    description: 'Sales role responsible for closing deals and managing customer relationships.',
    category: 'sales',
  },
  SDR: {
    acronym: 'SDR',
    fullName: 'Sales Development Representative',
    description: 'Sales role focused on outbound prospecting and lead qualification.',
    category: 'sales',
  },
  BDR: {
    acronym: 'BDR',
    fullName: 'Business Development Representative',
    description: 'Similar to SDR, focused on generating new business opportunities.',
    category: 'sales',
  },
  ASP: {
    acronym: 'ASP',
    fullName: 'Average Selling Price',
    description: 'The average price at which a product or service is sold.',
    category: 'sales',
  },
  QBR: {
    acronym: 'QBR',
    fullName: 'Quarterly Business Review',
    description: 'Regular meeting with customers to review progress, value delivered, and future plans.',
    category: 'sales',
  },

  // Product Metrics
  PMF: {
    acronym: 'PMF',
    fullName: 'Product-Market Fit',
    description: 'The degree to which a product satisfies strong market demand.',
    category: 'product',
  },
  MVP: {
    acronym: 'MVP',
    fullName: 'Minimum Viable Product',
    description: 'A product with just enough features to satisfy early customers and provide feedback.',
    category: 'product',
  },
  API: {
    acronym: 'API',
    fullName: 'Application Programming Interface',
    description: 'A set of protocols that allows different software applications to communicate.',
    category: 'product',
  },
  SLA: {
    acronym: 'SLA',
    fullName: 'Service Level Agreement',
    description: 'A commitment between service provider and customer defining service standards.',
    category: 'product',
  },
  MTTR: {
    acronym: 'MTTR',
    fullName: 'Mean Time To Recovery',
    description: 'Average time to restore service after a failure or incident.',
    category: 'product',
  },
  MTTF: {
    acronym: 'MTTF',
    fullName: 'Mean Time To Failure',
    description: 'Average time a system operates before failing.',
    category: 'product',
  },

  // Operations & Business
  GTM: {
    acronym: 'GTM',
    fullName: 'Go-to-Market',
    description: 'Strategy and tactics for launching and selling a product to customers.',
    category: 'operations',
  },
  TAM: {
    acronym: 'TAM',
    fullName: 'Total Addressable Market',
    description: 'The total market demand for a product or service.',
    category: 'operations',
  },
  SAM: {
    acronym: 'SAM',
    fullName: 'Serviceable Addressable Market',
    description: 'The portion of TAM that can be reached with current business model.',
    category: 'operations',
  },
  SOM: {
    acronym: 'SOM',
    fullName: 'Serviceable Obtainable Market',
    description: 'The realistic portion of SAM that can be captured.',
    category: 'operations',
  },
  ICP: {
    acronym: 'ICP',
    fullName: 'Ideal Customer Profile',
    description: 'Description of the perfect customer for your product or service.',
    category: 'operations',
  },
  OKR: {
    acronym: 'OKR',
    fullName: 'Objectives and Key Results',
    description: 'Goal-setting framework for defining and tracking objectives and outcomes.',
    category: 'operations',
  },
  KPI: {
    acronym: 'KPI',
    fullName: 'Key Performance Indicator',
    description: 'Measurable value demonstrating how effectively objectives are being achieved.',
    category: 'operations',
  },
  ROI: {
    acronym: 'ROI',
    fullName: 'Return on Investment',
    description: 'Ratio of net profit to cost of investment, expressed as a percentage.',
    category: 'financial',
  },
  'P&L': {
    acronym: 'P&L',
    fullName: 'Profit and Loss Statement',
    description: 'Financial statement summarizing revenues, costs, and expenses.',
    category: 'financial',
  },
  YoY: {
    acronym: 'YoY',
    fullName: 'Year over Year',
    description: 'Comparison of a statistic from one period to the same period the previous year.',
    category: 'general',
  },
  QoQ: {
    acronym: 'QoQ',
    fullName: 'Quarter over Quarter',
    description: 'Comparison of a statistic from one quarter to the previous quarter.',
    category: 'general',
  },
  MoM: {
    acronym: 'MoM',
    fullName: 'Month over Month',
    description: 'Comparison of a statistic from one month to the previous month.',
    category: 'general',
  },
  WoW: {
    acronym: 'WoW',
    fullName: 'Week over Week',
    description: 'Comparison of a statistic from one week to the previous week.',
    category: 'general',
  },

  // SaaS Specific
  SaaS: {
    acronym: 'SaaS',
    fullName: 'Software as a Service',
    description: 'Software delivery model where applications are hosted and provided over the internet.',
    category: 'general',
  },
  B2B: {
    acronym: 'B2B',
    fullName: 'Business to Business',
    description: 'Commercial transactions between businesses rather than consumers.',
    category: 'general',
  },
  B2C: {
    acronym: 'B2C',
    fullName: 'Business to Consumer',
    description: 'Commercial transactions between a business and individual consumers.',
    category: 'general',
  },
  SMB: {
    acronym: 'SMB',
    fullName: 'Small and Medium Business',
    description: 'Companies with fewer employees or revenue than large enterprises.',
    category: 'general',
  },
  MM: {
    acronym: 'MM',
    fullName: 'Mid-Market',
    description: 'Companies between SMB and enterprise in size and complexity.',
    category: 'general',
  },
  ENT: {
    acronym: 'ENT',
    fullName: 'Enterprise',
    description: 'Large organizations with complex needs and significant budgets.',
    category: 'general',
  },
};

/**
 * Get acronym definition by key
 */
export function getAcronymDefinition(acronym: string): AcronymDefinition | undefined {
  return ACRONYMS[acronym.toUpperCase()];
}

/**
 * Check if a word is a known acronym
 */
export function isKnownAcronym(word: string): boolean {
  return word.toUpperCase() in ACRONYMS;
}

/**
 * Get all acronyms in a category
 */
export function getAcronymsByCategory(category: AcronymDefinition['category']): AcronymDefinition[] {
  return Object.values(ACRONYMS).filter(a => a.category === category);
}

/**
 * Get all acronym keys
 */
export function getAllAcronymKeys(): string[] {
  return Object.keys(ACRONYMS);
}

/**
 * Create a regex pattern that matches any known acronym
 * Useful for finding acronyms in text
 */
export function createAcronymPattern(): RegExp {
  const acronymKeys = getAllAcronymKeys();
  // Sort by length (longest first) to match longer acronyms before shorter ones
  const sortedKeys = acronymKeys.sort((a, b) => b.length - a.length);
  // Word boundary matching for acronyms
  return new RegExp(`\\b(${sortedKeys.join('|')})\\b`, 'g');
}

export default ACRONYMS;
